### ISSUE TITLE
How do I use `sim.launch`?

### ISSUE THREAD

**Issue by adaldo** [jolilj/el2425_bitcraze#1]
It seems that you are writing some nice code here :D

I was wondering what is the launchfile `sim.launch` doing.
If I launch it by itself, it gives me

```
Traceback (most recent call last):
  File "/home/adaldo/el2425_ws/src/el2425_bitcraze/scripts/plotter.py", line 115, in <module>
    x = rospy.get_param("/crazyflie/position_handler/x")
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/client.py", line 462, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/jade/lib/python2.7/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: '/crazyflie/position_handler/x'
```

which means essentially that there does not exist a `rosparam` called `/crazyflie/position_handler/x`.

Perhaps `sim.launch` is meant to be launched together with something else? But if this is the case, why is `sim.launch` also running its own `position_handler.py`?

(No need to reply to this, we can discuss in person.)

**Comment by jolilj** [comment]
hehe namespace bug. Should work now! The simulator launch file run the algorithm for interpolating the goal points for the cf so that we can check that we get the right trajectories. You run it by
```
roslaunch el2425_bitcraze sim.launch x:=x0 y:=y0 z:=z0
```
Without params it defaults to the origin.

Then you can call the setgoal service and see the interpolated trajectory in , e.g.
```
rosservice call /crazyflie/setgoal 1.0 1.0 1.0
```

**Comment by adaldo** [comment]
Cool, it is working for me now!
